# Generated by Django 4.2.16 on 2024-11-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accesscontrol",
            fields=[
                ("AccessID", models.IntegerField(primary_key=True, serialize=False)),
                ("MemberID", models.IntegerField(blank=True, null=True)),
                ("SpaceID", models.IntegerField(blank=True, null=True)),
                ("AccessType", models.CharField(max_length=255)),
                ("AccessStart", models.DateTimeField()),
                ("AccessEnd", models.DateTimeField()),
            ],
            options={
                "db_table": "AccessControl",
            },
        ),
        migrations.CreateModel(
            name="Analytics",
            fields=[
                ("AnalyticsID", models.IntegerField(primary_key=True, serialize=False)),
                ("SpaceID", models.IntegerField(blank=True, null=True)),
                ("Date", models.TextField()),
                ("OccupancyRate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Revenue", models.DecimalField(decimal_places=2, max_digits=10)),
                ("LeadsGenerated", models.IntegerField()),
                ("FeedbackScore", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "Analytics",
            },
        ),
        migrations.CreateModel(
            name="Bookings",
            fields=[
                ("BookingID", models.IntegerField(primary_key=True, serialize=False)),
                ("SpaceID", models.IntegerField()),
                ("MemberID", models.IntegerField()),
                ("StartDate", models.TextField()),
                ("EndDate", models.TextField()),
                ("Status", models.TextField()),
            ],
            options={
                "db_table": "Bookings",
            },
        ),
        migrations.CreateModel(
            name="Campaigns",
            fields=[
                ("CampaignID", models.IntegerField(primary_key=True, serialize=False)),
                ("CampaignName", models.CharField(max_length=255)),
                ("AudienceTargeted", models.TextField()),
                ("Budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("StartDate", models.TextField()),
                ("EndDate", models.TextField()),
            ],
            options={
                "db_table": "Campaigns",
            },
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("EmployeeID", models.IntegerField(primary_key=True, serialize=False)),
                ("FirstName", models.CharField(max_length=255)),
                ("LastName", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=254)),
                ("Password", models.CharField(max_length=255)),
                ("Role", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Employees",
            },
        ),
        migrations.CreateModel(
            name="Members",
            fields=[
                ("MemberID", models.IntegerField(primary_key=True, serialize=False)),
                ("FirstName", models.CharField(max_length=255)),
                ("LastName", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=254)),
                ("Phone", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "Members",
            },
        ),
        migrations.CreateModel(
            name="Spaces",
            fields=[
                ("SpaceID", models.IntegerField(primary_key=True, serialize=False)),
                ("SpaceName", models.CharField(max_length=255)),
                ("Location", models.TextField()),
                ("Capacity", models.IntegerField()),
                ("Amenities", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Spaces",
            },
        ),
    ]
