# Generated by Django 4.2.16 on 2024-11-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("view", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spaces",
            old_name="SpaceName",
            new_name="Name",
        ),
        migrations.AddField(
            model_name="spaces",
            name="Occupation_Status",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spaces",
            name="Type",
            field=models.CharField(default="private cabin", max_length=255),
            preserve_default=False,
        ),
    ]
