# Generated by Django 4.2.16 on 2024-11-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("view", "0002_rename_spacename_spaces_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spaces",
            old_name="Occupation_Status",
            new_name="OccupationStatus",
        ),
        migrations.AddField(
            model_name="spaces",
            name="FloorPlan",
            field=models.CharField(default="Avaliable", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="spaces",
            name="Amenities",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="spaces",
            name="Location",
            field=models.CharField(max_length=255),
        ),
    ]
