# Generated by Django 4.2.16 on 2024-11-22 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("view", "0004_remove_spaces_floorplan_remove_spaces_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("StartDate", models.DateTimeField()),
                ("EndDate", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Company", models.CharField(blank=True, max_length=255, null=True)),
                ("GST", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("HourlyPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("MonthlyPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("DailyPrice", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SpaceID", models.CharField(max_length=100)),
                ("Type", models.CharField(max_length=50)),
                ("OccupationStatus", models.CharField(max_length=50)),
                ("Capacity", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Accesscontrol",
        ),
        migrations.DeleteModel(
            name="Analytics",
        ),
        migrations.DeleteModel(
            name="Bookings",
        ),
        migrations.DeleteModel(
            name="Campaigns",
        ),
        migrations.DeleteModel(
            name="Employees",
        ),
        migrations.DeleteModel(
            name="Members",
        ),
        migrations.DeleteModel(
            name="Spaces",
        ),
        migrations.AddField(
            model_name="booking",
            name="Member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="view.member"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="Space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="view.space"
            ),
        ),
    ]
