# Generated by Django 4.2.16 on 2024-11-23 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("view", "0005_booking_member_price_space_delete_accesscontrol_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessControl",
            fields=[
                ("AccessID", models.AutoField(primary_key=True, serialize=False)),
                ("AccessType", models.CharField(blank=True, max_length=50, null=True)),
                ("AccessStart", models.DateTimeField(blank=True, null=True)),
                ("AccessEnd", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("EventID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100)),
                ("Description", models.TextField(blank=True, null=True)),
                ("StartDateTime", models.DateTimeField(blank=True, null=True)),
                ("EndDateTime", models.DateTimeField(blank=True, null=True)),
                ("OrganizerID", models.IntegerField(blank=True, null=True)),
                ("Venue", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("FeedbackID", models.AutoField(primary_key=True, serialize=False)),
                ("Rating", models.IntegerField()),
                ("Comments", models.TextField(blank=True, null=True)),
                ("FeedbackDate", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("InvoiceID", models.AutoField(primary_key=True, serialize=False)),
                ("IssueDate", models.DateField(blank=True, null=True)),
                ("DueDate", models.DateField(blank=True, null=True)),
                ("Amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "TaxAmount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "AdditionalFees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("Status", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("MembershipID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=50)),
                ("Benefits", models.JSONField(blank=True, null=True)),
                ("AccessHours", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "MonthlyFee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("Validity", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("PaymentID", models.AutoField(primary_key=True, serialize=False)),
                ("PaymentDate", models.DateField(blank=True, null=True)),
                ("Amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "PaymentMethod",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("Status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "TransactionID",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "LateFee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "Invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="view.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PricePlan",
            fields=[
                ("PriceID", models.AutoField(primary_key=True, serialize=False)),
                ("Duration", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "Price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "MembershipDiscount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "SeasonalDiscount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Price",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="id",
        ),
        migrations.RemoveField(
            model_name="member",
            name="id",
        ),
        migrations.RemoveField(
            model_name="space",
            name="id",
        ),
        migrations.AddField(
            model_name="booking",
            name="BookingID",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="Status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="Address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="ContactNumber",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="Email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="IsActive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="member",
            name="LastLogin",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="MemberID",
            field=models.AutoField(
                default=django.utils.timezone.now, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="MembershipID",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="Name",
            field=models.CharField(default="name", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="space",
            name="Amenities",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="space",
            name="FloorPlan",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="space",
            name="Location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="space",
            name="Name",
            field=models.CharField(default="name", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="EndDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="Member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="view.member",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="StartDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="Company",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="GST",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="space",
            name="Capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="space",
            name="OccupationStatus",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="space",
            name="SpaceID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="priceplan",
            name="Space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="view.space"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="Member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="view.member",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="Booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="view.booking",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="Booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="view.booking",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="Member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="view.member",
            ),
        ),
        migrations.AddField(
            model_name="accesscontrol",
            name="Member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="view.member",
            ),
        ),
        migrations.AddField(
            model_name="accesscontrol",
            name="Space",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="view.space"
            ),
        ),
    ]
