# Generated by Django 4.2.16 on 2024-11-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("view", "0006_accesscontrol_event_feedback_invoice_membership_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Space",
            new_name="Spaces",
        ),
        migrations.AlterModelTable(
            name="spaces",
            table="Spaces",
        ),
    ]
