# Generated by Django 4.2.16 on 2024-11-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemberLogin",
            fields=[
                ("MemberLoginID", models.AutoField(primary_key=True, serialize=False)),
                ("MemberID", models.IntegerField()),
                ("Username", models.CharField(max_length=255, unique=True)),
                ("Password", models.CharField(max_length=255)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("LastLogin", models.DateTimeField(blank=True, null=True)),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Suspended", "Suspended"),
                            ("Deleted", "Deleted"),
                        ],
                        default="Active",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
