# Generated by Django 4.2.16 on 2024-11-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("MemberID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100)),
                (
                    "ContactNumber",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Address", models.CharField(blank=True, max_length=100, null=True)),
                ("Company", models.CharField(blank=True, max_length=100, null=True)),
                ("GST", models.CharField(blank=True, max_length=20, null=True)),
                ("MembershipID", models.IntegerField(blank=True, null=True)),
                ("PasswordHash", models.CharField(max_length=255)),
                ("PasswordSalt", models.CharField(max_length=255)),
                ("LastLogin", models.DateTimeField(blank=True, null=True)),
                ("IsActive", models.BooleanField(default=True)),
                (
                    "AadharID",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
            ],
            options={
                "db_table": "Members",
            },
        ),
        migrations.DeleteModel(
            name="MemberLogin",
        ),
    ]
